### ISSUE TITLE
Make compile with pioarduino 3.0.5 (ESP-IDF 5.1.4)

### ISSUE THREAD

**Issue by tueddy** [pschatzmann/ESP32-A2DP#605]
### Problem Description

Hi PSchatzmann,
due to lack of supporting Arduino 3 on PlatformIO i switched to [pioarduino](https://github.com/pioarduino/platform-espressif32). This works perfectly fine!
Framework versions: Arduino 3.0.5 , ESP-IDF 5.1.4

Compiling ESP32-A2DP i get some errors:

`.pio/libdeps/lolin_d32_pro_sdmmc_pe/ESP32-A2DP/src/BluetoothA2DPSink.cpp:285:41: error: 'portTickType' was not declared in this scope
  285 |                                        (portTickType)portMAX_DELAY)) {
      |                                         ^~~~~~~~~~~~
`
and
`C:/Users/dcars/.platformio/packages/framework-espidf@src-29cf07cc82e49157db19869ff2d1be3f/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos/portmacro.h:125:36: error: expected primary-expression before ')' token
  125 | #define portMAX_DELAY ( TickType_t ) 0xffffffffUL
      |          `

I changed this line

https://github.com/pschatzmann/ESP32-A2DP/blob/3624fe3f23c8a4d181f891910f5b62dc87a51105/src/BluetoothA2DPCommon.h#L94

to

`#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 1 , 4)`

and everything compiles. Can you fix it?

Thanks & best
Dirk

### Device Description

Lolin D32 pro

### Sketch

```cpp
demo sketch
```

### Provide your Version of the EP32 Arduino Core (or the IDF Version)

Arduino 3.0.5, ESP-IDF 5.1.4

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
can you share some minimal code to reproduce the issue ?
