### ISSUE TITLE
Error compiling libraries

### ISSUE THREAD

**Issue by podaen** [pschatzmann/ESP32-A2DP#339]
For 'ESP32 Dev Module(espressif_esp32) I am not able to compile anymore after updating this lib... Could you please look. All my warnings are out.

 > BluetoothA2DPSinkQueued.h: 9:7: error: redefinition of 'class BluetoothA2DPSinkQueued
>  class BluetoothA2DPSinkQueued *: public BluetoothA2DPSink {
>    ^~~~~~~~~~~~~~~~~~~~~~~
>  
> BluetoothA2DP.h:15: In file included from
> Hall_Alarm_Music_V5.ino:180: from
> BluetoothA2DPSinkQueued.h:9: note  previous definition of class BluetoothA2DPSinkQueued
>  class BluetoothA2DPSinkQueued *: public BluetoothA2DPSink {
>    ^~~~~~~~~~~~~~~~~~~~~~~

Before I had it working on ESP32 cores 2.0.4. Now I am on the latest 2.0.5 dev.

**Comment by podaen** [comment]
Sorry, it was because I imported evryting in my shetch. Now the error is gone.

```
#include <A2DPVolumeControl.h>
#include <BluetoothA2DP.h>
//#include <BluetoothA2DPCommon.h>
//#include <BluetoothA2DPSink.h>
//#include <BluetoothA2DPSinkQueued.h>
//#include <BluetoothA2DPSource.h>
//#include <SoundData.h>
```

**Comment by pschatzmann** [comment]
Actually, your right: multiple import should not give any errors.
I committed the related correction...

**Comment by podaen** [comment]
Phill, if you add includes=BluetoothA2DP.h to the library.properties file, than only that header is imported in to the code, when working with an Arduino IDE.

**Comment by pschatzmann** [comment]
I am aware of this setting, but I think it would be a bad choice to punish everyone who installs this library by making the compilation of all sketches slower. 

It is far better to give the user the choice to import the project when it is really needed.

**Comment by podaen** [comment]
Didn't know that was slower. Can the compiling time not be reduced with?

```
#ifndef _x_h //beginning of header file
#define _x_h

#endif// end of header file
```

**Comment by pschatzmann** [comment]
If you add this definition Arduino needs to include this file and all related files in all sketches. 
Your proposed guard does not help here. 

ps. this is identical with #pragma once
